---
title: "Analyzing natural area sensitivity thresholds for humans and species diversity in Alberta’s Capital City"
project:
  type: website
  output-dir: docs
navbar: right
theme: cosmo
date: "`r format(Sys.time(), '%d %B, %Y')`"
author: 
  - name: "Alex MacPhail"
    affiliation:
    - "Biodiversity Pathways Ltd."
  - name: "Catherine Shier"
    affiliation:
      - "City of Edmonton"
  - name: "Erin Bayne"
    affiliation:
      - "University of Alberta"
editor: visual
bibliography: references.bib
nocite: '@*'
toc: true
toc-depth: 3
toc-expand: true
toc-location: left
styles: styles.css
github: https://github.com/biodiversitypathways/coe
---

# Abstract

# Introduction

Urbanization, driven by globalization and industrialization, leads to higher population densities and significant changes in landscapes (@carnahan1974urbanization, @berry2008urbanization, @davis2015urbanization). However, urbanization also introduces anthropogenic challenges, such as light and noise pollution, which are closely tied to densely populated areas and have well-established negative effects on human, biodiversity (@sordello2020evidence) and ecosystem health. As cities expand, the need for humans to reconnect with nature becomes increasingly critical (@pyle2003nature, @buxton2024mental). This reinforces the need for accessible natural spaces within cities. In response, urban planners are integrating green spaces into cities by creating parks and preserving natural areas (@mata2020bringing). Whether urban green spaces can effectively sustain and represent native biodiversity is still being studied as urbanization evolves. Although managed natural areas and green spaces may offer critical habitats, excessive noise pollution can render these spaces unsuitable for species dependent on quiet environments for communication, reproduction, and survival. Even adaptable species face challenges when urban nature design is incomplete or poorly integrated, affecting their fitness and reproductive success.

Modern urban planning offers an opportunity to address these challenges in a holistic manner. By prioritizing quieter, functional urban spaces through district planning and zoning bylaws, urban designs can reduce noise pollution while offering residents easy access to amenities, including grocery stores, schools, and parks. Public transit improvements indirectly mitigates traffic noise, contributing to healthier urban soundscapes. To reshape urban infrastructure effectively, it is essential to understand the temporal changes and behavioural impacts of noise pollution on both humans and wildlife, which requires continuous, robust environmental monitoring. Advances in acoustic and image monitoring technologies now make such environmental assessments more feasible and cost-effective (@buxton2018pairing). However, current monitoring practices often rely on resource-intensive methods, such as moving equipment by trucks, which can contradict environmental stewardship principles.

In Alberta's 2021 Census, 82.3% of the population resided in urban areas, with a significant concentration in census metropolitan areas (CMAs) like Edmonton. The City of Edmonton has committed to enhancing its biodiversity through various strategic initiatives, including the [Natural Connections Strategic Plan, 2007](https://www.edmonton.ca/sites/default/files/public-files/assets/PDF/Natural_Connections_-_Strategic_Plan_JUNE_09.pdf?cb=1738466394) and the [Biodiversity Action Plan, 2009](https://www.edmonton.ca/sites/default/files/public-files/assets/PDF/Edmonton_Biodiversity_Action_Plan_Final.PDF). In conjunction with the tenants of these plan, this study outlines a long-term environmental monitoring program that also redefines how monitoring is conducted. By implementing zero-emission transportation and employing autonomous recording units, this program will target both noisy and non-noisy and high and low quality habitat areas of Edmonton to monitor the cities' evolving soundscape as infrastructure changes. These efforts align with the city’s broader vision for increased walking and cycling infrastructure, reducing traffic noise, and fostering sustainable practices.

This study aims to assess the proportion of natural areas in Edmonton that exceed noise sensitivity thresholds for both people and biodiversity, mapping these thresholds to guide future urban planning decisions. By shifting infrastructure investments from noise mitigation toward sustainable transit, we can create urban environments that are not only quieter but also more harmonious for both human and wildlife populations. Achieving this vision will position Edmonton as a leader in urban biodiversity preservation, sustainable urban living, and environmental stewardship.

# Methods

## Study area and design

### Zero-emissions fieldwork

## Mapping noise thresholds

# Results

# Discussion
